logger_options:
  log_path: logs                                  # Can be abs path
  log_level: 20                                   # info

youtube_downloader_options:
  preferred_video_format: mp4
  preferred_audio_codec: mp3
  default_video_quality: 720p
  max_video_duration_seconds: 1200                # 20 min
  max_audio_duration_seconds: 7200                # 2 hours
  max_file_size: 45M                              # Telegram bots can send up to 50M
  ffmpeg_location: null                           # null will try to get from env as ffmpeg

telegram_bot_options:
  text_timeout_seconds: 30
  video_timeout_seconds: 300                      # 5 min  
  audio_timeout_seconds: 300                      # 5 min

youtube_search_options:
  max_results: 5                                  # Limit search results with 5